/*
===============================================================================
05 - Magnitude Analysis
===============================================================================
Purpose: Compare measure values across dimensions (grouped totals).
Tables:  gold.fact_sales, gold.dim_customers, gold.dim_products
===============================================================================
*/

-- Find total customers by country
SELECT
	COUNT(customer_id) AS total_customers,
	country
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find total customers by gender
SELECT
	COUNT(customer_id) AS total_customers,
	gender
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Find total products by category
SELECT
	category,
	COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- What is the average cost in each category?
SELECT
	category,
	AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;

-- What is the total revenue generated by each category?
SELECT
	SUM(f.sales_amount) AS total_revenue,
	p.category
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p
	ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

-- Find the total revenue generated by each customer
SELECT
	SUM(s.sales_amount) AS total_revenue,
	c.customer_key,
	c.first_name,
	c.last_name
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_customers AS c
	ON s.customer_key = c.customer_key
GROUP BY c.customer_key, c.first_name, c.last_name
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across countries?
SELECT
	c.country,
	SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
	ON f.customer_key = c.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC;